SUI-13 - Add Avatar Selects
Faithlife/styled-ui pull request #381
Opened 2020-11-09 19:36 UTC by zmckinnon

# [SUI-13](https://faithlife.atlassian.net/browse/SUI-13)

I am working on a People lookup component for Church Management.  This component uses an extremely common UX pattern of showing avatars for both the drop down options and the selected options.

### Screenshot
<img width="1057" alt="Screen Shot 2020-11-09 at 1 15 08 PM" src="https://user-images.githubusercontent.com/2788269/98586107-db4e3180-228d-11eb-8335-c6178e6cd473.png">

2020-11-09 20:03 UTC, korbinancell requested changes

2020-11-09 20:03 UTC, korbinancell commented on components/text-input-v2/select.jsx
> +export const AvatarSelect = React.forwardRef(({ components = {}, ...props }, ref) => {
Instead of re-wrapping and re-exporting out wrappers we should consider just exporting the `avatarComponents` and lettings consumers pass those in themselves. I am also in favor of just making these the default option and multi option components, because it seems that they won't break any existing selects.

cc @RobertBolender thoughts?

2020-11-09 20:04 UTC, korbinancell commented on components/text-input-v2/select.jsx
> +export const AvatarSelect = React.forwardRef(({ components = {}, ...props }, ref) => {
Also thanks for your contribution to styled-ui 🎉

2020-11-09 20:15 UTC, zmckinnon commented on components/text-input-v2/select.jsx
> +export const AvatarSelect = React.forwardRef(({ components = {}, ...props }, ref) => {
I considered this as well.  It's more of a documentation thing if we go that direction.  Interested in more people's thoughts.

2020-11-09 23:01 UTC, RobertBolender commented on components/text-input-v2/select.jsx
> +export const AvatarSelect = React.forwardRef(({ components = {}, ...props }, ref) => {
For the internal `avatarComponents` themselves, these look beautifully clean and are an excellent use of our theme 👍 

For the shape of the exports, my preferences strongly align with the two options that Korbin recommended:
A: Export `avatarComponents` and let consumers pass them in to the various `components` props.
B: Make these `Option` and `MultiValue` components the defaults for all our selects (if we can verify this won't break existing consumers).

2020-11-09 23:06 UTC, RobertBolender requested changes

2020-11-09 23:06 UTC, RobertBolender commented on components/text-input-v2/select.jsx
> +	return <Select ref={ref} {...props} components={{ ...avatarComponents }} />;
If you do stick with this pattern of export, each of these components should spread their respective `components` props:
`components={{ ... avatarComponents, ...components }}`

2020-11-10 14:59 UTC, zmckinnon commented on components/text-input-v2/select.jsx
> +export const AvatarSelect = React.forwardRef(({ components = {}, ...props }, ref) => {
I did A.  I am tempted to do B, but it feels like it COULD be breaking if the data has an `avatar` property, so I left this out.  If we ever want to change this in the future, should be easy peasy.

2020-11-10 18:50 UTC, RobertBolender approved these changes

2020-11-11 00:55 UTC, merged