Add ImageWell component
Faithlife/styled-ui pull request #433
Opened 2021-01-11 23:10 UTC by zachsnoek

This PR adds an ImageWell component. #431

2021-01-12 19:44 UTC, zachsnoek commented
The current upper-right corner icon is based off of the icon in the Facilities/Resources tab:

![Screen Shot 2021-01-12 at 11 40 30 AM](https://user-images.githubusercontent.com/26049962/104364347-55d44100-54cb-11eb-82e5-342d1df03733.png)

ChMS also uses an image well with a camera icon instead:

![Screen Shot 2021-01-12 at 11 40 41 AM](https://user-images.githubusercontent.com/26049962/104364399-6389c680-54cb-11eb-82b5-b720ab2d83e9.png)

Should we default to the X icon but allow that icon to be changed with an `icon` prop?

2021-01-13 19:28 UTC, bryanrsmith requested changes
> Should we default to the X icon but allow that icon to be changed with an icon prop?

We should ask design which use cases this should accommodate and make sure the happy path is right.

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/component.jsx
> +import * as Styled from './styled';
Please use styled system components and avoid the pattern of grouping styled components into a single file.

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/component.jsx
> +			<ImageWellBase previewUrl={previewUrl}>
Seems like this will render a button with no click handler, which is undesirable.

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/component.jsx
> +					<Styled.RemoveIconContainer onClick={() => onRemoveImage?.()}>
Click handlers need to go on buttons, and we should not render a button that does nothing (so, either conditionally render the button or make the handler required)

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/component.jsx
> +			<ImageWellBase previewUrl={previewUrl}>
Also, shouldn't you be able to click the image again to choose a different one?

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/component.jsx
> +	fitPreviewToSquare,
I'm a little surprised that we want this to be configurable. Has Design confirmed that the inconsistency is desirable?

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/component.jsx
> +						<X className="image-well_remove-icon" />
Prefer styled components APIs or use a selector

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/styled.jsx
> +import { colors, thickness, fonts } from '../shared-styles';
use theme. shared-styles is pending removal.

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/styled.jsx
> +	box-sizing: content-box;
Why?

2021-01-13 19:28 UTC, bryanrsmith commented on components/image-well/styled.jsx
> +	height: ${fixedContainerHeight};
This seems fragile; would 100% or flex be more appropriate?

2021-01-14 00:36 UTC, zachsnoek commented on components/image-well/component.jsx
> +	fitPreviewToSquare,
[Confirmed this with design](https://www.flowdock.com/app/logos/styled-ui/threads/BbgtEItR72govOHEZB5UYnVDFb9).

2021-01-14 17:06 UTC, zachsnoek commented on components/image-well/component.jsx
> +			<ImageWellBase previewUrl={previewUrl}>
One version of the ImageWell in ChMS shows the X icon but displays the image in a light box when the preview is clicked (and removes the image when the X is clicked). Another version shows the camera icon and prompts you to choose a new image regardless of where you clicked the image well.

I added a [commit](https://github.com/Faithlife/styled-ui/pull/433/commits/4793ae37eb0de087fbe1d0005c9f6215c5ee4b97) to add this behavior in and documented it; let me know if this behavior isn't what we want or if it should be implemented some other way.

2021-01-14 23:25 UTC, zachsnoek commented
I've added `ImageWell.PreviewContent` so that we can support custom controls over the preview image as shown in [this spec](https://app.zeplin.io/project/5b10273d413156335e1b6743/screen/5cc8b19387477603a84fa4c0). Custom content shown when there is no `previewUrl` is now wrapped in `ImageWell.SelectContent`.

2021-01-15 21:33 UTC, RobertBolender commented on components/image-well/image-well-icons.jsx
> +		e.stopPropagation();
For both of these icons, is it ever appropriate for the consumer to *not* supply an onClick handler? Won't that result in the click being swallowed by this stopPropagation and not bubble up to the ImageWell click handler?

If the function is required, it should be marked as a required propType, and we shouldn't have the default `() => {}`

2021-01-15 22:08 UTC, zachsnoek commented on components/image-well/image-well-icons.jsx
> +		e.stopPropagation();
Not supplying an `onClick` handler could be useful if you want to show the camera icon and have that call `onSelectImage` when clicked, but also provide some other icon with a custom `onClick`. Not providing the camera's `onClick` handler should just cause the event to bubble up:

```jsx
<ImageWell
    onSelectImage={() => alert("image well clicked")}
>
    <ImageWell.PreviewContent>
        <ImageWell.CameraIcon /> {/* clicking this calls onSelectImage */}
        <StarIcon onClick={(e) => {
            e.stopPropagation();
            alert("star clicked");
        }}/>
    </ImageWell.PreviewContent>
</ImageWell>
```

However, we do want to prevent bubbling on the default icons.

2021-01-15 22:33 UTC, RobertBolender commented on components/image-well/image-well-icons.jsx
> +export const CameraIcon = ({ onClick = () => {} }) => (
My previous comment still stands. These two icon components are exported, and they *must* always be passed an onClick handler, so they should have it defined as required on their propTypes and not have a default `() => {}`.

```js
CameraIcon.propTypes = {
  onClick: PropTypes.func.isRequired
}
```

2021-01-15 22:34 UTC, RobertBolender commented on components/image-well/component.jsx
> +	const handleIconClick = (e, cb) => {
Naming nit: Faithlife guidelines say to avoid abbreviations:
https://wiki.lrscorp.net/Avoid_Abbreviations

2021-01-15 23:06 UTC, RobertBolender commented on components/image-well/image-well-base.jsx
> +	height: ${fixedContainerHeight};
Two more questions:

1. Why 116px in particular?
2. Could this `div` instead be a `Box` so that it will accept styled-system layout props, allowing for overriding these values?

2021-01-15 23:12 UTC, zachsnoek commented on components/image-well/image-well-base.jsx
> +	height: ${fixedContainerHeight};
1. I took those styles from [ChurchManagement](https://git.faithlife.dev/Logos/ChurchManagement/blob/master/chms-tool/src/components/EditRecordWizard/FormComponents/Image/styles.less#L15-L16); otherwise there is no particular reason.
2. I'll make that change :+1:

2021-01-15 23:13 UTC, RobertBolender commented on components/image-well/image-well-base.jsx
> +	height: ${fixedContainerHeight};
> otherwise there is no particular reason.

Also, did I miss somewhere in this PR where that exported const is used, or can it be removed?

2021-01-15 23:16 UTC, zachsnoek commented on components/image-well/image-well-base.jsx
> +	height: ${fixedContainerHeight};
> Also, did I miss somewhere in this PR where that exported const is used, or can it be removed?

They're also being used in [`image-well-preview.jsx`](https://github.com/Faithlife/styled-ui/pull/433/files#diff-0c759ef95ed80b40c6265308877d51f3d9ac956dd5b738c5b5d4e2aac8ab38eeR7-R8).

2021-01-15 23:19 UTC, RobertBolender commented on components/image-well/image-well-base.jsx
> +	height: ${fixedContainerHeight};
Thanks.
Strong recommendation: have that component *also* extend `Box` instead of `div`, and have the top-level component pass along it's width/height props to that component as well. You'll also be able to use styled-system props for what is currently in the `style` prop.

2021-01-16 00:31 UTC, zachsnoek commented
I added a "primary" variant to match [this](https://app.zeplin.io/project/5b10273d413156335e1b6743/screen/5cc8b19387477603a84fa4c0) spec and what's currently in ChMS. If this isn't an appropriate use of a variant I can remove it.

2021-01-16 01:09 UTC, RobertBolender commented
> I added a "primary" variant to match [this](https://app.zeplin.io/project/5b10273d413156335e1b6743/screen/5cc8b19387477603a84fa4c0) spec and what's currently in ChMS. If this isn't an appropriate use of a variant I can remove it.

The concept of a `variant` assumes that there is more than one. We currently only have one style, so I would say that adding a `variant` prop is premature.

2021-01-18 22:27 UTC, zachsnoek commented
The dashed border is now being created with this tool: https://kovart.github.io/dashed-border-generator/. If this seems reasonable for now, I can try and make it work better with the `border` `styled-system` prop.

2021-01-20 21:31 UTC, merged