Jest!
Faithlife/styled-ui pull request #485
Opened 2021-05-14 21:57 UTC by korbinancell

Will probably need some configuration in netlify as well. Not sure.

There are quite a few todos in here. This pr is already way too big, so I left aXe compliance and some component reconfiguring for a later pr.

If I couldn't test that the component worked I at least tested that it existed.

2021-05-14 22:21 UTC, RobertBolender commented
FYI: `render`, `axe`, and `screen` are not exported from `test-utils`
https://app.netlify.com/sites/faithlife-styled-ui/deploys/609ef25624017600081d8fa4

2021-05-14 22:36 UTC, korbinancell commented
Whoops, yea that was me being lazy. I just need to remove that file entirely and import from the different packages directly.

2021-05-17 15:39 UTC, rmjohnson requested changes

2021-05-17 15:39 UTC, rmjohnson commented on components/__tests__/import-tests.test.js
> +	it.skip('should not crash when imported', () => {
Do we really need this test?

2021-05-17 15:39 UTC, rmjohnson commented on components/__tests__/layout-primitives.test.js
> +describe('Layout Primitives', () => {
You might consider moving these to their own test files to maintain `component-name.test.js(x)` pattern to make the tests easier to find.

2021-05-17 15:39 UTC, rmjohnson commented on components/__tests__/switch.test.jsx
> +	// TODO: make aXe compatible
nit: you might consider making a github issue for this.

2021-05-17 15:39 UTC, rmjohnson commented on components/accordion/__tests__/accordion.test.jsx
> +			expect(onExpansion.mock.calls[0][0]).toEqual(expectedExpandedSections);
`calls[0][0]` feels a bit mysterious here to me. Are you looking for `toHaveBeenCalledWith`?

2021-05-17 15:39 UTC, rmjohnson commented on components/check-box/__tests__/check-box.test.jsx
> +	it('should respond to user click', () => {
Another couple of easy tests might be setting `isChecked` and asserting the underlying checkboxes are indeed checked / unchecked.

2021-05-17 15:39 UTC, rmjohnson commented on components/help-box/component.jsx
> +					<Styled.CloseButton aria-label="Close" onClick={handleClose}>
:golfclap:

2021-05-17 15:39 UTC, rmjohnson commented on components/loading-spinner/__tests__/loading-spinner.test.jsx
> +	it('is truthy', () => {
What? No interaction tests? :trollface:

2021-05-17 15:39 UTC, rmjohnson commented on components/parameter-sentence/__tests__/parameter-sentence.test.jsx
> +					// formatValue={val => `${val}%`}
commented out code

2021-05-17 15:39 UTC, rmjohnson commented on components/__tests__/switch.test.jsx
> +import { render, axe, screen, userEvent } from '../../test-utils';
Missed this one =)

2021-05-17 15:39 UTC, rmjohnson commented on components/parameter-sentence/__tests__/parameter-sentence.test.jsx
> +	it('s Input is interact-able', () => {
I think I see what you're going for here but unfortunately since the test output doesn't seem to include "it" it looks a little weird / confusing.

![image](https://user-images.githubusercontent.com/249152/118515174-0193d480-b6ea-11eb-8bc6-9280a8a062f8.png)

Maybe just `Input is..`?

2021-05-17 15:39 UTC, rmjohnson commented on components/parameter-sentence/__tests__/parameter-sentence.test.jsx
> +					accessibilityLabel={'Percent of income to tithe'}
Would be good to include this label in the `getByRole` call to add some coverage for it.

2021-05-17 15:39 UTC, rmjohnson commented on components/parameter-sentence/__tests__/parameter-sentence.test.jsx
> +		userEvent.click(screen.getByText('annual'));
Do we not have an accessible role on this?

2021-05-17 15:39 UTC, rmjohnson commented on components/popover/__tests__/tooltip.test.jsx
> +		await waitFor(() => expect(screen.getByText('hovered!')).toBeVisible());
I'd expect (heh...) we could use `expect(await screen.findByText(...` to achieve the same thing.

2021-05-17 15:39 UTC, rmjohnson commented on components/simple-toast/__tests__/simple-toast.test.jsx
> +describe('SimpleToast', () => {
Consider adding a test using https://jestjs.io/docs/timer-mocks#advance-timers-by-time to test out the `showTime`.

2021-05-17 15:39 UTC, rmjohnson commented on components/slider/__tests__/slider.test.jsx
> +	// TODO: this is sort of an accessiblity nightmare currently
😬

2021-05-17 15:39 UTC, rmjohnson commented on jest.config.js
> +		// '\\.(css|less)$': require.resolve('./__mocks__/styleMock.js'),
Commented out code.

2021-05-17 15:39 UTC, rmjohnson commented on package.json
> +		"test": "npm run build && npm run test:ci && npm run eslint && npm run stylelint",
I'll defer to you but it's a little weird to me that the `test` command runs the `build` and lint.

2021-05-17 15:54 UTC, mdombrowski1997 commented on package.json
> +		"test": "npm run build && npm run test:ci && npm run eslint && npm run stylelint",
☝🏽 I believe Jest builds the code for you, so building before testing doesn't change anything

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/collapse/__tests__/collapse.test.jsx
> +	it('should respond to user click', () => {
Is this test name misleading?  We're not testing user input or clicking, we're testing that the `isOpen` prop shows/hides the children.  Should we update the name to match what is being tested?

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/date-picker-input/__tests__/date-picker-input.test.jsx
> +		expect.hasAssertions();
This [expect.hasAssertions()](https://jestjs.io/docs/expect#expecthasassertions) is in a lot of these tests.  It appears to offer safety when we're delegating our assertions to functions called within the test function.  However, in this (and I believe all other) tests, we call `expect` directly, so this ever-present call feels more like clutter than a help.  Should we drop these calls to `expect.hasAssertions()`?

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/date-picker/__tests__/date-picker.test.jsx
> +	// eslint-disable-next-line no-unsanitized/method
This lint rule seems to be unhelpful in tests.  Calling "unsafe" code is expected, and is 0 risk since they are tests.  Should we disable this rule for all `.test.jsx` files for ease of use?

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/popover/__tests__/tooltip.test.jsx
> +		await waitFor(() => expect(screen.getByText('hovered!')).toBeVisible());
Does `findByText` assert that the element is visible though?  I would image `findByText` would find the element (which appears to be always present in the DOM since `getByText` isn't throwing), then if it isn't immediately visible, would fail.  I actually think I find this current version more clear as to what we're asserting (assuming I'm correct here)

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/share-dialog/__tests__/share-dialog.test.jsx
> +		expect(ShareDialog).toBeTruthy();
Are we asserting here that the `import` was successful?  If so, why?

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/share-dialog/__tests__/share-dialog.test.jsx
> +		expect(ShareDialog).toBeTruthy();
I see the same for `SequencedTab` and `Tab`.  Are we ensuring that we don't change the name or shape of our `export`s?

2021-05-17 16:24 UTC, mdombrowski1997 commented on components/share-dialog/__tests__/share-dialog.test.jsx
> +		expect.hasAssertions();
This feels redundant here in particular where the entire test *is* a single assertion

2021-05-17 20:40 UTC, korbinancell commented on components/accordion/__tests__/accordion.test.jsx
> +			expect(onExpansion.mock.calls[0][0]).toEqual(expectedExpandedSections);
I had originally experimented with using snapshots to test this data vs hard coding the expected data, looks like I left this around.

2021-05-17 20:47 UTC, korbinancell commented on components/parameter-sentence/__tests__/parameter-sentence.test.jsx
> +		userEvent.click(screen.getByText('annual'));
It appears we don't from the output in the test. This component might need to be revisited now that it has been updated to v6 🤔

2021-05-17 20:49 UTC, korbinancell commented on components/popover/__tests__/tooltip.test.jsx
> +		await waitFor(() => expect(screen.getByText('hovered!')).toBeVisible());
These tests are skipped b/c something about popper.js does not play nicely with jest. I might just have to mock popper and go from there.

2021-05-17 20:54 UTC, korbinancell commented on components/simple-toast/__tests__/simple-toast.test.jsx
> +describe('SimpleToast', () => {
These are not tested b/c of some weirdness with refs in jest testing. B/c they are not rendered with react-dom the refs are never set. (Which is why I think that popovers are having issues). So I kinda just skipped this. However, now that I think about it we are using useImperativeHandle to tack on all of the methods, so maybe that will still all happen even without the working ref?

2021-05-17 20:56 UTC, korbinancell commented on components/collapse/__tests__/collapse.test.jsx
> +	it('should respond to user click', () => {
copy paste got me again

2021-05-17 20:57 UTC, korbinancell commented on components/date-picker-input/__tests__/date-picker-input.test.jsx
> +		expect.hasAssertions();
This one is kinda a force of habit. Our linking in giving land requires it (and actually found a couple of tests that weren't actually checking anything when we first added it).

2021-05-17 21:03 UTC, korbinancell commented on components/share-dialog/__tests__/share-dialog.test.jsx
> +		expect(ShareDialog).toBeTruthy();
It is mainly to make sure that we don't lose any children of these new Component.ChildComponent style components along the way. It might be overkill normally, but for something like styled-ui with so many varied users making sure we don't lose components unexpectantly is always nice to have.

2021-05-18 17:43 UTC, korbinancell commented on components/check-box/__tests__/check-box.test.jsx
> +	it('should respond to user click', () => {
There actually isn't an underlying checkbox element, it is all buttons and svgs and aria roles

2021-05-18 20:16 UTC, rmjohnson approved these changes
Love it! :shipit:

2021-05-18 21:18 UTC, merged