Publish and update version history v6.9.3
Faithlife/styled-ui pull request #527
Opened 2022-02-08 15:57 UTC by SaltyPineapple

2022-02-08 16:07 UTC, Auk14HP requested changes

2022-02-08 16:14 UTC, SaltyPineapple commented on package.json
> +		"@popperjs/core": "^2.11.2",
I did not pull from `styled-ui` before making this PR, I didn't realize I needed to since these changes were already made. I am not sure why this is a part of this PR

2022-02-08 16:28 UTC, Auk14HP commented on package.json
> +		"@popperjs/core": "^2.11.2",
You should rebase this atop the latest from origin/master

2022-10-21 18:57 UTC, korbinancell reviewed
Review to get this out of my notifications.

2025-02-28 07:01 UTC, closed without merging