Improve `Modal.FooterButtons` API
Faithlife/styled-ui pull request #529
Opened 2022-02-09 20:56 UTC by TyMick

Part of [FLCOM-8106](https://faithlife.atlassian.net/browse/FLCOM-8106).

Implements the more flexible `Modal.FooterButtons` API discussed in [this Styled UI Flowdock thread](https://www.flowdock.com/app/logos/styled-ui/threads/bFNRZ1UAThh0VnkNx9fpBbrrOPm) and deprecates the old `commitButton`, `cancelButton`, and `deleteButton` props in favor of it.

A summary of the API change:

- Before
  
  ```jsx
  <Modal.Footer>
    <Modal.FooterButtons
      commitButton={{ text: 'Save', onClick: () => alert('Saved') }}
      cancelButton={{ text: 'Cancel', onClick: () => setState({ modal: !state.modal }) }}
      deleteButton={{ text: 'Delete Forever', onClick: () => alert('Deleted') }}
    />
  </Modal.Footer>
  ```
  
- After
  
  ```jsx
  <Modal.Footer>
    <Modal.FooterButtons>
      <Modal.FooterButton variant="primary" onClick={() => alert('Saved')}>
        Save
      </Modal.FooterButton>
      <Modal.FooterButton variant="secondary" onClick={() => setState({ modal: !state.modal })}>
        Cancel
      </Modal.FooterButton>
      <Modal.FooterButton
        variant="danger"
        onClick={() => alert('Deleted')}
        marginInlineEnd="auto"
      >
        Delete Forever
      </Modal.FooterButton>
    </Modal.FooterButtons>
  </Modal.Footer>
  ```

024fc0993b0b8a4cadf04566d246d6a7338debbf is actually the only fix I originally needed for [FLCOM-8106](https://faithlife.atlassian.net/browse/FLCOM-8106), but I think I'll use the new API for that case anyway, since I like it better. 🥳

## Important review points

I'd recommend walking through this PR one commit at a time when reviewing. Each step is pretty atomic.

- Was 3f8bce08ff027cc860d6271710a33b58ed14a755 a good decision? Removing the element measuring will make the component much more maintainable, and the `useFullWidthButtons` behavior was only triggering on screens less than 320 CSS pixels wide, so these full-width buttons wouldn't even be used on an iPhone 5/SE. If a dev is expecting buttons to have enough text that they need to think about making the buttons full-width, they should probably build their own special handling.

- Once I refactored in a4b25298f01d716d320cfc90ee8f919bb6afef2c to use the `gap` property (which is [safe to use](https://caniuse.com/flexbox-gap) now that it's been added to iOS Safari), moving a third button to the left side on its own became as easy as adding `marginInlineEnd="auto"` (the language-direction-agnostic alternative to `marginRight="auto"`) to it. We'd [discussed](https://www.flowdock.com/app/logos/styled-ui/threads/bFNRZ1UAThh0VnkNx9fpBbrrOPm) making `Modal.FooterButtons` automatically shove the last child button to the left if there are at least three, but if the CSS is this easy, is requiring the dev to enter it a fine alternative? This would also allow for different groupings of buttons (say, two buttons on each side).

2022-02-09 21:09 UTC, korbinancell commented
> requiring the dev to enter it

What do you think of adding a `floatLeft` or `alignLeft` prop that applies this css?

2022-02-09 21:19 UTC, TyMick commented
Maybe `floatAcross` (or `floatOpposite`) since I [switched](https://github.com/Faithlife/styled-ui/pull/529/commits/da1d955796cba8791c4613b3e9ce7be359b4e51f) the right/left properties to logical properties?

2022-02-09 22:38 UTC, TyMick commented
I've gone with `floatAcross` for now. (And edited past commits to do so, to keep the commits organized. Sorry if that throws off anyone's review.)

2022-02-09 23:43 UTC, TyMick commented
Rebasing to pull in #530 (to make it easier to <code><a href="https://github.com/wclr/yalc">yalc</a> publish</code>).

2022-02-10 18:01 UTC, PatrickNausha requested changes

2022-02-10 18:08 UTC, PatrickNausha commented
> Was https://github.com/Faithlife/styled-ui/commit/3f8bce08ff027cc860d6271710a33b58ed14a755 a good decision? Removing the element measuring will make the component much more maintainable, and the useFullWidthButtons behavior was only triggering on screens less than 320 CSS pixels wide, so these full-width buttons wouldn't even be used on an iPhone 5/SE.

This logic seems sound to me. If `useFullWidthButtons` is never `true` in practice, the code seems effectively dead. In theory a consumer could make a modal as narrow as they want, shrinking it below 320px, but I'm not sure why they would.

2022-02-11 22:50 UTC, TyMick commented on components/modal/ModalFooterButtons.jsx
> +	if (commitButton | cancelButton | deleteButton && children) {
Oh! I totally meant to use `||` 😂 Thanks for catching. Had the parentheses in there, too, till Prettier took them out.

2022-02-11 23:00 UTC, TyMick commented on components/modal/ModalFooterButtons.jsx
> +function mapButtonToJsx(buttonObject, variant, floatAcross = false) {
Oh yeah, so much better 🎉

2022-02-11 23:01 UTC, TyMick commented on catalog/modal/variations.md
> +				<Modal.FooterButton variant="secondary" onClick={() => setState({ modal: !state.modal })}>
💯

2022-02-11 23:45 UTC, TyMick commented on catalog/modal/variations.md
> -			/>
[`7d3bda7`](https://github.com/Faithlife/styled-ui/pull/529/commits/7d3bda754511c37508a995f61241c3fe372e7674)

2022-02-11 23:46 UTC, TyMick commented on components/modal/ModalFooterButton.jsx
> +	 * languages). It does this by adding `margin-inline-end: auto` to its CSS.
[`bbd61df`](https://github.com/Faithlife/styled-ui/pull/529/commits/bbd61dffe4840799ce322233340d792cd00f31b0)

2022-02-11 23:49 UTC, TyMick commented on catalog/modal/variations.md
> +				<Modal.FooterButton variant="secondary" onClick={() => setState({ modal: !state.modal })}>
[`ae15243`](https://github.com/Faithlife/styled-ui/pull/529/commits/ae1524343b6f863c50c852dcf187d0c1c74b97d8)

2022-02-11 23:50 UTC, TyMick commented
Thanks so much for the review, @PatrickNausha! Would you like to take one more pass?

2022-02-15 18:43 UTC, PatrickNausha commented on components/modal/ModalFooterButtons.jsx
> +const LegacyFooterButton = ({ buttonObject, variant, floatAcross = false }) => (
Nit: I prefer `function` declarations for modules that have multiple functions at the top level. This is because I get to ignore [TDZ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz) problems by leveraging [function declaration hoisting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#function_declaration_hoisting).

2022-02-15 19:00 UTC, PatrickNausha commented
I just saw [the documentation page](https://deploy-preview-529--faithlife-styled-ui.netlify.app/#/modal/documentation) for the first time. Should `Modal.FooterButton` be on that page?

2022-02-15 19:21 UTC, PatrickNausha commented on components/modal/ModalFooterButtons.jsx
> +	}
I think you need `key` props here or every consumer will start seeing an error in the console.

```suggestion
	if (commitButton) {
		buttons.push(<LegacyFooterButton key="commit" buttonObject={commitButton} variant="primary" />);
		if (cancelButton) {
			buttons.push(<LegacyFooterButton key="cancel" buttonObject={cancelButton} variant="secondary" />);
		}
		if (deleteButton) {
			buttons.push(<LegacyFooterButton key="delete" buttonObject={deleteButton} variant="danger" floatAcross />);
		}
	} else {
		if (deleteButton) {
			buttons.push(<LegacyFooterButton key="delete" buttonObject={deleteButton} variant="dangerSpecial" />);
		}
		if (cancelButton) {
			buttons.push(<LegacyFooterButton key="cancel" buttonObject={cancelButton} variant="secondary" />);
		}
	}
```

2022-02-18 23:07 UTC, TyMick commented on components/modal/ModalFooterButtons.jsx
> +const LegacyFooterButton = ({ buttonObject, variant, floatAcross = false }) => (
I have indeed wondered why this works in React files. 🤔 But yeah, even if it does work, the pattern causes enough pause that the reduction in readability probably isn't worth saving a couple lines of code.

2022-02-18 23:34 UTC, TyMick commented on catalog/modal/variations.md
> +## Legacy `Modal.FooterButtons` API
[`28c1c09`](https://github.com/Faithlife/styled-ui/pull/529/commits/28c1c09269e09f4c7448d286a8dca8f01a8488b2)

2022-02-18 23:34 UTC, TyMick commented on catalog/modal/variations.md
> +The legacy `Modal.FooterButtons` API using `commitButton`, `cancelButton`, and `deleteButton` props has been deprecated in favor of using `Modal.FooterButton` child components, as demonstrated on the
[`28c1c09`](https://github.com/Faithlife/styled-ui/pull/529/commits/28c1c09269e09f4c7448d286a8dca8f01a8488b2)

2022-02-18 23:36 UTC, TyMick commented on components/modal/ModalFooterButtons.jsx
> +	}
[`4c1dfa3`](https://github.com/Faithlife/styled-ui/pull/529/commits/4c1dfa3c000d3fb99d2e1b474c58df39a6fda0a0)

2022-02-18 23:39 UTC, TyMick commented on components/modal/ModalFooterButtons.jsx
> +	}
I went with `"commit1"`, `"cancel1"`, `"delete1"`, `"delete2"`, and `"cancel2"`, in case a `commitButton` gets added or removed sometime during the lifecycle, since the `deleteButton` should change when that happens. Doubt that situation would actually occur, but may as well.

2022-02-21 18:11 UTC, PatrickNausha commented on components/modal/ModalFooterButtons.jsx
> +const LegacyFooterButton = ({ buttonObject, variant, floatAcross = false }) => (
> I have indeed wondered why this works in React files. 🤔

I'm not sure exactly what you're asking, but the TDZ becomes an issue when you reference an uninitialized variable. E.g. this is fine
```js
function print() {
    console.log(foo);
}

const foo = 'foo';
print();
```
but this is not
```js
function print() {
    console.log(foo);
}

print();
const foo = 'foo';
```

2022-02-21 18:26 UTC, PatrickNausha commented on components/modal/ModalFooterButtons.jsx
> +	}
I don't understand why the different keys are necessary. The code should work just fine with `key="commit"`, `key="cancel"`, and `key="delete"` even if you change the `*button` props throughout the component's lifetime. I think key props are mostly used to [help the DOM reconciliation algorithm](https://reactjs.org/docs/reconciliation.html#recursing-on-children), not avoid rerenders completely.

2022-02-21 18:39 UTC, PatrickNausha approved these changes
Looks great except my last comment regarding key props on https://github.com/Faithlife/styled-ui/pull/529#discussion_r811358495

2022-02-23 21:49 UTC, TyMick commented on components/modal/ModalFooterButtons.jsx
> +	}
[`485c7e5`](https://github.com/Faithlife/styled-ui/pull/529/commits/485c7e5ae208756b560b58cd8dd7999ebf18975e)

2022-02-23 23:07 UTC, merged